### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by NikitaBliznyuk** [danilchican/ASOO#1]
I like your idea. But I still hope, that I won't need it. :D 
You can add, for example, online payment for orders.

**Comment by danilchican** [comment]
> You can add, for example, online payment for orders.

Online payment? Hmm.. Hardly to introduce it into web-service and integrate with each faculty. 
Many legal questions.

**Comment by NikitaBliznyuk** [comment]
But sounds cool. :)
If you integrate it in our university system, you can try to add it.
