### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by trtpo** [danilchican/ASOO#2]
Vladislav,

Please, do not include features that are not to be implemented in your functional requirements section! (what your user will not be able to do) - this info goes into introduction. 

And also, I'd recommend to re-structure your repository. Please, don't put every project file into root directory - it looks messy!

**Comment by danilchican** [comment]
Thanks for reply. I will re-structure repo and edit requirements.

**Comment by danilchican** [comment]
Functional requirements with not implemented features were deleted.
Re-structured repo.
